import express from 'express';
import { config } from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import axios from 'axios';
import { generateBackend } from './src/generators/aiClient.js';
import { parseURL } from './src/parsers/urlParser.js';

config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = process.env.PORT || 4000;

app.use(express.json({ limit: '10mb' }));
app.use(express.static(path.join(__dirname, 'public')));

// ── Generate endpoint ─────────────────────────────────────────────
app.post('/api/generate', async (req, res) => {
  const { type, content, fileName, fileType, url, provider, supabase } = req.body;

  if (!type || (type === 'file' && !content) || (type === 'url' && !url)) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  if (provider) process.env.AI_PROVIDER = provider;

  try {
    let parsedInput;
    if (type === 'url') {
      parsedInput = await parseURL(url);
    } else {
      const MAX_CHARS = 12000;
      const truncated = content.length > MAX_CHARS;
      parsedInput = {
        type: 'file',
        fileType: fileType || 'json',
        fileName: fileName || 'input',
        content: truncated ? content.slice(0, MAX_CHARS) + '\n...[truncated]' : content,
        truncated,
      };
    }

    if (supabase?.url && supabase?.anonKey) {
      parsedInput.supabase = supabase;
    }

    const files = await generateBackend(parsedInput);
    res.json({ success: true, files });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Scrape URL preview ────────────────────────────────────────────
app.post('/api/preview-url', async (req, res) => {
  const { url } = req.body;
  if (!url) return res.status(400).json({ error: 'URL is required' });
  try {
    const parsed = await parseURL(url);
    res.json({ success: true, preview: parsed.content.slice(0, 800) + '...', title: parsed.title });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Deploy to Render ──────────────────────────────────────────────
app.post('/api/deploy', async (req, res) => {
  const { files, githubToken, renderToken, repoName } = req.body;

  if (!files || !githubToken || !renderToken || !repoName) {
    return res.status(400).json({ error: 'Missing required fields.' });
  }

  const slug = repoName.toLowerCase().replace(/[^a-z0-9-]/g, '-').replace(/-+/g, '-').slice(0, 40);
  const ghHeaders = {
    Authorization: `token ${githubToken}`,
    'Content-Type': 'application/json',
    'User-Agent': 'UniversalBackendGenerator',
  };

  // FIX: Set headers before first write to avoid streaming issues
  res.setHeader('Content-Type', 'application/x-ndjson');
  res.setHeader('Cache-Control', 'no-cache');
  res.flushHeaders();

  try {
    res.write(JSON.stringify({ step: 1, message: '🔍 Verifying GitHub account...' }) + '\n');
    const userRes = await axios.get('https://api.github.com/user', { headers: ghHeaders });
    const githubUsername = userRes.data.login;

    res.write(JSON.stringify({ step: 2, message: `📁 Creating GitHub repo: ${slug}...` }) + '\n');
    try {
      await axios.delete(`https://api.github.com/repos/${githubUsername}/${slug}`, { headers: ghHeaders });
      await new Promise(r => setTimeout(r, 2000));
    } catch (_) { }

    await axios.post('https://api.github.com/user/repos', {
      name: slug, description: 'Generated by Universal Backend Generator', private: false, auto_init: false,
    }, { headers: ghHeaders });
    await new Promise(r => setTimeout(r, 1500));

    // ── Step 1: Normalize ALL paths first (strip src/ prefix) ────────
    // Must happen BEFORE package.json check — AI often generates
    // src/package.json which would otherwise bypass our guarantee below
    const normalized = {};
    for (const [filePath, content] of Object.entries(files)) {
      const cleanPath = filePath.replace(/^src\//, '');
      normalized[cleanPath] = content;
    }

    // ── Step 2: Guarantee package.json at root with correct fields ──
    const requiredDeps = {
      express: '^4.18.0', dotenv: '^16.4.0', cors: '^2.8.5',
      helmet: '^7.0.0', 'express-rate-limit': '^7.0.0',
      'express-mongo-sanitize': '^2.2.0', hpp: '^0.2.3',
      joi: '^17.11.0', bcryptjs: '^2.4.3',
      jsonwebtoken: '^9.0.0', morgan: '^1.10.0',
      winston: '^3.11.0', uuid: '^9.0.0',
    };
    let pkg = {};
    try { pkg = JSON.parse(normalized['package.json'] || '{}'); } catch (_) { }
    pkg.name = pkg.name || slug;
    pkg.version = pkg.version || '1.0.0';
    pkg.type = 'module';
    pkg.main = 'index.js';
    pkg.scripts = { ...(pkg.scripts || {}), start: 'node index.js' };
    pkg.engines = { node: '>=18.0.0' };
    pkg.dependencies = { ...requiredDeps, ...(pkg.dependencies || {}) };
    normalized['package.json'] = JSON.stringify(pkg, null, 2);

    // ── Step 3: Stub any missing local imports ─────────────────────
    // AI often imports files it forgot to generate — Node crashes on start
    function resolveRelative(fromFile, importPath) {
      const dir = fromFile.includes('/') ? fromFile.split('/').slice(0, -1).join('/') : '';
      const parts = (dir ? dir + '/' + importPath : importPath).split('/');
      const out = [];
      for (const p of parts) {
        if (p === '..') out.pop();
        else if (p !== '.') out.push(p);
      }
      const joined = out.join('/');
      return joined.endsWith('.js') ? joined : joined + '.js';
    }
    for (const [filePath, content] of Object.entries(normalized)) {
      if (typeof content !== 'string') continue;
      for (const [, imp] of content.matchAll(/from\s+['"](\.\.?\/[^'"]+)['"]/g)) {
        const resolved = resolveRelative(filePath, imp);
        if (!normalized[resolved]) {
          const name = resolved.split('/').pop().replace('.js', '');
          if (/apperror/i.test(name)) {
            normalized[resolved] = `class AppError extends Error {\n  constructor(message, statusCode, errorCode) {\n    super(message);\n    this.statusCode = statusCode || 500;\n    this.errorCode = errorCode || 'INTERNAL_ERROR';\n    this.isOperational = true;\n  }\n}\nexport default AppError;\n`;
          } else if (/asynchandler/i.test(name)) {
            normalized[resolved] = `const asyncHandler = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);\nexport default asyncHandler;\n`;
          } else if (/roles/i.test(name)) {
            normalized[resolved] = `const roles = (...allowed) => (req, res, next) => {\n  if (!req.user || !allowed.includes(req.user.role)) return res.status(403).json({ success: false, message: 'Forbidden.' });\n  next();\n};\nexport default roles;\n`;
          } else if (/model/i.test(resolved)) {
            normalized[resolved] = `import Joi from 'joi';\nexport const ${name}Schema = Joi.object({ name: Joi.string().min(2).max(100).required() });\n`;
          } else if (/service/i.test(resolved)) {
            normalized[resolved] = `import AppError from '../utils/AppError.js';\nconst getAll = async () => [];\nconst getById = async (id) => { throw new AppError('Not found', 404); };\nconst create = async (body) => ({ id: crypto.randomUUID(), ...body });\nexport default { getAll, getById, create };\n`;
          } else {
            normalized[resolved] = `export default {};\n`;
          }
        }
      }
    }

    // ── Step 4: Build final file set ────────────────────────────────
    const normalizedFiles = {
      ...normalized,
      '.gitignore': `node_modules/\n.env\n.env.local\nlogs/\n*.log\n`,
      'render.yaml': `services:\n  - type: web\n    name: ${slug}\n    runtime: node\n    buildCommand: npm install\n    startCommand: node index.js\n    envVars:\n      - key: NODE_ENV\n        value: production\n      - key: PORT\n        value: 10000`,
    };

    res.write(JSON.stringify({ step: 3, message: `📤 Pushing ${Object.keys(normalizedFiles).length} files to GitHub...` }) + '\n');
    for (const [filePath, content] of Object.entries(normalizedFiles)) {
      const fileContent = typeof content === 'string' ? content : JSON.stringify(content, null, 2);
      await axios.put(
        `https://api.github.com/repos/${githubUsername}/${slug}/contents/${filePath}`,
        { message: `Add ${filePath}`, content: Buffer.from(fileContent).toString('base64') },
        { headers: ghHeaders }
      );
    }

    const repoUrl = `https://github.com/${githubUsername}/${slug}`;
    res.write(JSON.stringify({ step: 4, message: '🚀 Creating Render service...' }) + '\n');

    const renderHeaders = { Authorization: `Bearer ${renderToken}`, 'Content-Type': 'application/json', Accept: 'application/json' };
    const ownerRes = await axios.get('https://api.render.com/v1/owners?limit=1', { headers: renderHeaders });
    const ownerId = ownerRes.data[0]?.owner?.id;
    if (!ownerId) throw new Error('Could not get Render account ID.');

    // FIX: envSpecificDetails required by Render API for non-static non-docker services
    const jwtSecret = [...Array(64)].map(() => Math.floor(Math.random() * 16).toString(16)).join('');
    const serviceRes = await axios.post('https://api.render.com/v1/services', {
      type: 'web_service',
      name: slug,
      ownerId,
      repo: repoUrl,
      branch: 'main',
      autoDeploy: 'yes',
      // envVars must be TOP LEVEL — not inside serviceDetails
      envVars: [
        { key: 'NODE_ENV', value: 'production' },
        { key: 'PORT', value: '10000' },
        { key: 'JWT_SECRET', value: jwtSecret },
        { key: 'JWT_EXPIRE', value: '15m' },
        { key: 'JWT_REFRESH_EXPIRE', value: '30d' },
        { key: 'ALLOWED_ORIGINS', value: `https://${slug}.onrender.com` },
      ],
      serviceDetails: {
        runtime: 'node',
        buildCommand: 'npm install',
        startCommand: 'node index.js',
        plan: 'free',
        region: 'oregon',
        pullRequestPreviewsEnabled: 'no',
        envSpecificDetails: {
          buildCommand: 'npm install',
          startCommand: 'node index.js',
        },
      },
    }, { headers: renderHeaders });

    const serviceId = serviceRes.data.service?.id;
    const serviceUrl = serviceRes.data.service?.serviceDetails?.url || `https://${slug}.onrender.com`;

    res.write(JSON.stringify({ step: 5, message: '⏳ Render is building your backend...' }) + '\n');
    if (serviceId) {
      for (let i = 0; i < 24; i++) {
        await new Promise(r => setTimeout(r, 5000));
        try {
          const deploys = await axios.get(`https://api.render.com/v1/services/${serviceId}/deploys?limit=1`, { headers: renderHeaders });
          const status = deploys.data[0]?.deploy?.status;
          res.write(JSON.stringify({ step: 5, message: `⏳ Build status: ${status || 'starting'}...` }) + '\n');
          if (status === 'live') break;
          if (status === 'build_failed' || status === 'update_failed') throw new Error('Render build failed. Check your Render dashboard for logs.');
        } catch (e) { if (e.message.includes('build failed')) throw e; }
      }
    }

    res.write(JSON.stringify({ step: 6, done: true, message: '✅ Deployed!', liveUrl: serviceUrl, githubUrl: repoUrl }) + '\n');
    res.end();
  } catch (err) {
    const msg = err.response?.data?.message || err.message;
    res.write(JSON.stringify({ error: msg }) + '\n');
    res.end();
  }
});

app.listen(PORT, () => {
  console.log(`\n🚀 Universal Backend Generator running at http://localhost:${PORT}\n`);
});